CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE firms(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),legal_name varchar(180) NOT NULL,display_name varchar(160) NOT NULL,slug varchar(80) NOT NULL UNIQUE,document varchar(40),email varchar(254) NOT NULL,phone varchar(40),website varchar(300),timezone varchar(80) NOT NULL DEFAULT 'America/Sao_Paulo',locale varchar(20) NOT NULL DEFAULT 'pt-BR',setup_completed boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE firm_branding(firm_id uuid PRIMARY KEY REFERENCES firms(id) ON DELETE CASCADE,system_title varchar(120) NOT NULL DEFAULT 'Legal Workspace',firm_display_name varchar(160) NOT NULL,logo_light_storage_key varchar(255),logo_dark_storage_key varchar(255),favicon_storage_key varchar(255),login_background_storage_key varchar(255),primary_color varchar(7) NOT NULL DEFAULT '#23395B',secondary_color varchar(7) NOT NULL DEFAULT '#152238',accent_color varchar(7) NOT NULL DEFAULT '#C89B3C',sidebar_style varchar(20) NOT NULL DEFAULT 'dark' CHECK(sidebar_style IN('dark','light','brand')),border_radius_style varchar(20) NOT NULL DEFAULT 'soft' CHECK(border_radius_style IN('square','soft','rounded')),support_email varchar(254),support_phone varchar(40),website varchar(300),client_portal_title varchar(120) NOT NULL DEFAULT 'Portal do Cliente',client_portal_welcome_text varchar(500) NOT NULL DEFAULT 'Acompanhe as informações compartilhadas pelo escritório.',updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid);
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,name varchar(120) NOT NULL,email varchar(254) NOT NULL,password_hash text NOT NULL,active boolean NOT NULL DEFAULT true,last_login_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),disabled_at timestamptz,deleted_at timestamptz,deleted_by uuid,UNIQUE(firm_id,email),UNIQUE(id,firm_id));
ALTER TABLE firm_branding ADD CONSTRAINT branding_updated_by_fk FOREIGN KEY(updated_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT;
CREATE TABLE sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,user_id uuid NOT NULL,token_hash bytea NOT NULL UNIQUE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),last_seen_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(user_id,firm_id) REFERENCES users(id,firm_id) ON DELETE CASCADE);
CREATE INDEX sessions_lookup_idx ON sessions(token_hash,expires_at);
CREATE TABLE roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,name varchar(80) NOT NULL,description varchar(300),system boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(firm_id,name),UNIQUE(id,firm_id));
CREATE TABLE permissions(key varchar(80) PRIMARY KEY,description varchar(300) NOT NULL);
CREATE TABLE role_permissions(role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,permission_key varchar(80) NOT NULL REFERENCES permissions(key) ON DELETE CASCADE,PRIMARY KEY(role_id,permission_key));
CREATE TABLE user_roles(user_id uuid NOT NULL,role_id uuid NOT NULL,firm_id uuid NOT NULL,PRIMARY KEY(user_id,role_id),FOREIGN KEY(user_id,firm_id) REFERENCES users(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(role_id,firm_id) REFERENCES roles(id,firm_id) ON DELETE CASCADE);

CREATE TABLE legal_areas(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,name varchar(100) NOT NULL,active boolean NOT NULL DEFAULT true,UNIQUE(firm_id,name),UNIQUE(id,firm_id));
CREATE TABLE matter_types(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,key varchar(80) NOT NULL,name varchar(120) NOT NULL,active boolean NOT NULL DEFAULT true,UNIQUE(firm_id,key),UNIQUE(id,firm_id));
CREATE TABLE clients(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,type varchar(16) NOT NULL CHECK(type IN('person','company')),name varchar(180) NOT NULL,legal_name varchar(180),trade_name varchar(180),document varchar(40),email varchar(254),phone varchar(40),birth_date date,address jsonb NOT NULL DEFAULT '{}',notes text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,deleted_by uuid,UNIQUE(id,firm_id));
CREATE INDEX clients_firm_name_idx ON clients(firm_id,lower(name)) WHERE deleted_at IS NULL;
CREATE TABLE contacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,client_id uuid,name varchar(180) NOT NULL,type varchar(30) NOT NULL,email varchar(254),phone varchar(40),document varchar(40),notes text,created_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(id,firm_id),FOREIGN KEY(client_id,firm_id) REFERENCES clients(id,firm_id) ON DELETE RESTRICT);

CREATE TABLE matters(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,type varchar(40) NOT NULL CHECK(type IN('judicial_process','administrative_process','legal_consultation','contract','advisory','arbitration','extrajudicial','internal_legal_project','other')),internal_number varchar(80) NOT NULL,title varchar(220) NOT NULL,description text,legal_area_id uuid,matter_type_id uuid,status varchar(20) NOT NULL DEFAULT 'draft' CHECK(status IN('draft','active','on_hold','closing','archived')),priority varchar(16) NOT NULL DEFAULT 'normal' CHECK(priority IN('low','normal','high','critical')),responsible_user_id uuid,confidentiality varchar(20) NOT NULL DEFAULT 'normal' CHECK(confidentiality IN('normal','team_only','partners_only','restricted')),opened_at date NOT NULL DEFAULT CURRENT_DATE,closed_at date,archived_at timestamptz,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,deleted_by uuid,UNIQUE(firm_id,internal_number),UNIQUE(id,firm_id),FOREIGN KEY(legal_area_id,firm_id) REFERENCES legal_areas(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(matter_type_id,firm_id) REFERENCES matter_types(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(responsible_user_id,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE INDEX matters_firm_status_idx ON matters(firm_id,status,updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX matters_internal_idx ON matters(firm_id,internal_number);
CREATE TABLE matter_legal_process(matter_id uuid PRIMARY KEY,firm_id uuid NOT NULL,case_number varchar(100),court varchar(180),court_division varchar(180),jurisdiction varchar(120),district varchar(120),state varchar(80),country varchar(80) DEFAULT 'Brasil',case_class varchar(160),subject varchar(220),claim_value_cents bigint CHECK(claim_value_cents IS NULL OR claim_value_cents>=0),distribution_date date,external_system_reference varchar(180),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE);
CREATE INDEX legal_process_case_idx ON matter_legal_process(firm_id,case_number);
CREATE TABLE matter_access(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),matter_id uuid NOT NULL,firm_id uuid NOT NULL,user_id uuid,role_id uuid,access_level varchar(12) NOT NULL CHECK(access_level IN('read','write','manage')),CHECK((user_id IS NULL)<>(role_id IS NULL)),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(user_id,firm_id) REFERENCES users(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(role_id,firm_id) REFERENCES roles(id,firm_id) ON DELETE CASCADE);
CREATE TABLE matter_parties(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),matter_id uuid NOT NULL,firm_id uuid NOT NULL,party_type varchar(40) NOT NULL,client_id uuid,contact_id uuid,name varchar(180) NOT NULL,document varchar(40),role varchar(40) NOT NULL,side varchar(20) NOT NULL CHECK(side IN('client','opposing','third_party','neutral')),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(client_id,firm_id) REFERENCES clients(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(contact_id,firm_id) REFERENCES contacts(id,firm_id) ON DELETE RESTRICT);
CREATE TABLE matter_notes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),matter_id uuid NOT NULL,firm_id uuid NOT NULL,content text NOT NULL,visibility varchar(12) NOT NULL CHECK(visibility IN('team','private')),created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);

CREATE TABLE custom_field_definitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,entity_type varchar(20) NOT NULL CHECK(entity_type IN('matter','client')),key varchar(80) NOT NULL,label varchar(120) NOT NULL,type varchar(16) NOT NULL CHECK(type IN('text','textarea','number','date','boolean','select')),required boolean NOT NULL DEFAULT false,options jsonb NOT NULL DEFAULT '[]',active boolean NOT NULL DEFAULT true,UNIQUE(firm_id,entity_type,key));
CREATE TABLE custom_field_values(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,definition_id uuid NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,entity_id uuid NOT NULL,value jsonb NOT NULL,UNIQUE(definition_id,entity_id));
CREATE TABLE tags(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,name varchar(60) NOT NULL,color varchar(7) NOT NULL DEFAULT '#64748B',UNIQUE(firm_id,name),UNIQUE(id,firm_id));
CREATE TABLE entity_tags(tag_id uuid NOT NULL REFERENCES tags(id) ON DELETE CASCADE,firm_id uuid NOT NULL,entity_type varchar(20) NOT NULL CHECK(entity_type IN('matter','client','document')),entity_id uuid NOT NULL,PRIMARY KEY(tag_id,entity_type,entity_id));

CREATE TABLE document_folders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid,name varchar(120) NOT NULL,sort_order integer NOT NULL DEFAULT 0,UNIQUE(id,firm_id),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE);
CREATE TABLE documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid,client_id uuid,folder_id uuid,title varchar(220) NOT NULL,description text,category varchar(40) NOT NULL,current_version_id uuid,client_visible boolean NOT NULL DEFAULT false,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,deleted_by uuid,UNIQUE(id,firm_id),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(client_id,firm_id) REFERENCES clients(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(folder_id,firm_id) REFERENCES document_folders(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE TABLE document_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),document_id uuid NOT NULL,firm_id uuid NOT NULL,version_number integer NOT NULL CHECK(version_number>0),original_file_name varchar(255) NOT NULL,storage_key varchar(255) NOT NULL UNIQUE,mime_type varchar(120) NOT NULL,size_bytes bigint NOT NULL CHECK(size_bytes>0),checksum varchar(64) NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),notes varchar(1000),UNIQUE(document_id,version_number),UNIQUE(id,firm_id),FOREIGN KEY(document_id,firm_id) REFERENCES documents(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
ALTER TABLE documents ADD CONSTRAINT current_version_fk FOREIGN KEY(current_version_id,firm_id) REFERENCES document_versions(id,firm_id) ON DELETE RESTRICT;
CREATE INDEX documents_firm_matter_idx ON documents(firm_id,matter_id,created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE workflow_definitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_type_id uuid,name varchar(160) NOT NULL,description text,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,firm_id),FOREIGN KEY(matter_type_id,firm_id) REFERENCES matter_types(id,firm_id) ON DELETE RESTRICT);
CREATE TABLE workflow_stages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workflow_id uuid NOT NULL,firm_id uuid NOT NULL,name varchar(120) NOT NULL,description text,color varchar(7) NOT NULL DEFAULT '#64748B',sort_order integer NOT NULL,checklist jsonb NOT NULL DEFAULT '[]',default_role_id uuid,on_enter_tasks jsonb NOT NULL DEFAULT '[]',UNIQUE(workflow_id,sort_order),UNIQUE(id,firm_id),FOREIGN KEY(workflow_id,firm_id) REFERENCES workflow_definitions(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(default_role_id,firm_id) REFERENCES roles(id,firm_id) ON DELETE RESTRICT);
CREATE TABLE workflow_transitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workflow_id uuid NOT NULL,firm_id uuid NOT NULL,from_stage_id uuid NOT NULL,to_stage_id uuid NOT NULL,name varchar(100) NOT NULL,FOREIGN KEY(workflow_id,firm_id) REFERENCES workflow_definitions(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(from_stage_id,firm_id) REFERENCES workflow_stages(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(to_stage_id,firm_id) REFERENCES workflow_stages(id,firm_id) ON DELETE CASCADE);
CREATE TABLE workflow_instances(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid NOT NULL,workflow_id uuid NOT NULL,current_stage_id uuid NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(id,firm_id),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(workflow_id,firm_id) REFERENCES workflow_definitions(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(current_stage_id,firm_id) REFERENCES workflow_stages(id,firm_id) ON DELETE RESTRICT);
CREATE TABLE matter_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,name varchar(160) NOT NULL,matter_type_id uuid,legal_area_id uuid,default_workflow_id uuid,custom_fields jsonb NOT NULL DEFAULT '{}',default_folders jsonb NOT NULL DEFAULT '[]',default_tasks jsonb NOT NULL DEFAULT '[]',default_tags jsonb NOT NULL DEFAULT '[]',active boolean NOT NULL DEFAULT true,FOREIGN KEY(matter_type_id,firm_id) REFERENCES matter_types(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(legal_area_id,firm_id) REFERENCES legal_areas(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(default_workflow_id,firm_id) REFERENCES workflow_definitions(id,firm_id) ON DELETE RESTRICT);

CREATE TABLE deadlines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid NOT NULL,title varchar(200) NOT NULL,description text,due_at timestamptz NOT NULL,status varchar(16) NOT NULL DEFAULT 'open' CHECK(status IN('open','completed','cancelled')),priority varchar(16) NOT NULL DEFAULT 'normal' CHECK(priority IN('low','normal','high','critical')),assigned_to uuid,created_by uuid NOT NULL,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,firm_id),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(assigned_to,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE INDEX deadlines_firm_due_idx ON deadlines(firm_id,status,due_at);
CREATE TABLE tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid,title varchar(200) NOT NULL,description text,assigned_to uuid,status varchar(20) NOT NULL DEFAULT 'todo' CHECK(status IN('todo','in_progress','blocked','done','cancelled')),priority varchar(16) NOT NULL DEFAULT 'normal' CHECK(priority IN('low','normal','high','critical')),due_at timestamptz,workflow_instance_id uuid,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(id,firm_id),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(assigned_to,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(workflow_instance_id,firm_id) REFERENCES workflow_instances(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE INDEX tasks_firm_status_idx ON tasks(firm_id,status,due_at);
CREATE TABLE hearings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid NOT NULL,title varchar(180) NOT NULL,type varchar(80) NOT NULL,scheduled_at timestamptz NOT NULL,location varchar(220),virtual_meeting_url varchar(500),responsible_user_id uuid,notes text,status varchar(20) NOT NULL DEFAULT 'scheduled' CHECK(status IN('scheduled','completed','cancelled','rescheduled')),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(responsible_user_id,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE INDEX hearings_firm_scheduled_idx ON hearings(firm_id,status,scheduled_at);
CREATE TABLE calendar_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid,title varchar(180) NOT NULL,type varchar(40) NOT NULL,start_at timestamptz NOT NULL,end_at timestamptz,location varchar(220),created_by uuid NOT NULL,FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);

CREATE TABLE matter_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid NOT NULL,type varchar(60) NOT NULL,summary varchar(500) NOT NULL,resource_type varchar(40),resource_id uuid,actor_id uuid NOT NULL,client_visible boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(actor_id,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE INDEX matter_events_timeline_idx ON matter_events(firm_id,matter_id,created_at DESC);
CREATE TABLE matter_closures(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid NOT NULL UNIQUE,closure_reason varchar(20) NOT NULL CHECK(closure_reason IN('completed','settlement','dismissed','transferred','withdrawn','cancelled','other')),outcome varchar(180),closed_at date NOT NULL,summary text,pending_tasks_count integer NOT NULL,pending_deadlines_count integer NOT NULL,financial_pending boolean NOT NULL,archived_by uuid NOT NULL,archived_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE RESTRICT,FOREIGN KEY(archived_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE TABLE matter_financial_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,matter_id uuid NOT NULL,type varchar(20) NOT NULL CHECK(type IN('fee','expense','court_cost','reimbursement','success_fee','payment')),amount_cents bigint NOT NULL CHECK(amount_cents>=0),description varchar(300) NOT NULL,due_date date,paid_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(created_by,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);

CREATE TABLE portal_users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,client_id uuid NOT NULL,email varchar(254) NOT NULL,password_hash text NOT NULL,active boolean NOT NULL DEFAULT true,last_login_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(firm_id,email),UNIQUE(id,firm_id),FOREIGN KEY(client_id,firm_id) REFERENCES clients(id,firm_id) ON DELETE CASCADE);
CREATE TABLE portal_sessions(token_hash bytea PRIMARY KEY,firm_id uuid NOT NULL,portal_user_id uuid NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(portal_user_id,firm_id) REFERENCES portal_users(id,firm_id) ON DELETE CASCADE);
CREATE TABLE portal_access(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,portal_user_id uuid NOT NULL,matter_id uuid NOT NULL,summary_visible boolean NOT NULL DEFAULT true,timeline_visible boolean NOT NULL DEFAULT false,appointments_visible boolean NOT NULL DEFAULT true,UNIQUE(portal_user_id,matter_id),FOREIGN KEY(portal_user_id,firm_id) REFERENCES portal_users(id,firm_id) ON DELETE CASCADE,FOREIGN KEY(matter_id,firm_id) REFERENCES matters(id,firm_id) ON DELETE CASCADE);
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,user_id uuid NOT NULL,type varchar(50) NOT NULL,title varchar(180) NOT NULL,message varchar(500) NOT NULL,resource_type varchar(40),resource_id uuid,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(user_id,firm_id) REFERENCES users(id,firm_id) ON DELETE CASCADE);
CREATE INDEX notifications_user_idx ON notifications(firm_id,user_id,read_at,created_at DESC);
CREATE TABLE audit_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,user_id uuid,action varchar(80) NOT NULL,resource_type varchar(40) NOT NULL,resource_id uuid,metadata jsonb NOT NULL DEFAULT '{}',ip_address inet,user_agent varchar(500),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(user_id,firm_id) REFERENCES users(id,firm_id) ON DELETE RESTRICT);
CREATE INDEX audit_firm_created_idx ON audit_events(firm_id,created_at DESC);

INSERT INTO permissions(key,description) VALUES
('firm.manage','Manage firm settings'),('branding.manage','Manage branding'),('users.read','Read users'),('users.manage','Manage users'),('clients.read','Read clients'),('clients.create','Create clients'),('clients.update','Update clients'),('clients.archive','Archive clients'),('matter.read','Read matters'),('matter.create','Create matters'),('matter.update','Update matters'),('matter.archive','Archive matters'),('matter.reopen','Reopen matters'),('document.read','Read documents'),('document.upload','Upload documents'),('document.update','Update documents'),('document.delete','Delete documents'),('deadline.read','Read deadlines'),('deadline.manage','Manage deadlines'),('task.read','Read tasks'),('task.manage','Manage tasks'),('workflow.read','Read workflows'),('workflow.manage','Manage workflows'),('finance.read','Read finance'),('finance.manage','Manage finance'),('audit.read','Read audit'),('archive.read','Read archive'),('portal.manage','Manage portal');
